#ifndef TEE_DEFINES_H
#define TEE_DEFINES_H

#define TEE_OPENSESSION         (0x00)
#define TEE_CLOSESESSION        (0x01)
#define TEE_INVOKECMD           (0x02)

#define TEE_ARGS_BASE                  0xA0020000
#define TEE_OFFSET_OP_ARGS            (0x00)
#define TEE_OFFSET_SESSIONID_ARGS     (0x04)
#define TEE_OFFSET_PARAMTYPE_ARGS     (0x08)
#define TEE_OFFSET_PARAM0_0_ARGS      (0x0C)
#define TEE_OFFSET_PARAM0_1_ARGS      (0x10)
#define TEE_OFFSET_PARAM1_0_ARGS      (0x14)
#define TEE_OFFSET_PARAM1_1_ARGS      (0x18)
#define TEE_OFFSET_PARAM2_0_ARGS      (0x1C)
#define TEE_OFFSET_PARAM2_1_ARGS      (0x20)
#define TEE_OFFSET_PARAM3_0_ARGS      (0x24)
#define TEE_OFFSET_PARAM3_1_ARGS      (0x28)
#define TEE_OFFSET_CMDID_ARGS         (0x2C)
#define TEE_OFFSET_RETURN_ARGS        (0x00)


#define TEE_OP_ARGS            (TEE_ARGS_BASE+TEE_OFFSET_OP_ARGS)
#define TEE_SESSIONID_ARGS     (TEE_ARGS_BASE+TEE_OFFSET_SESSIONID_ARGS)
#define TEE_PARAMTYPE_ARGS     (TEE_ARGS_BASE+TEE_OFFSET_PARAMTYPE_ARGS)
#define TEE_PARAM0_0_ARGS      (TEE_ARGS_BASE+TEE_OFFSET_PARAM0_0_ARGS)
#define TEE_PARAM0_1_ARGS      (TEE_ARGS_BASE+TEE_OFFSET_PARAM0_1_ARGS)
#define TEE_PARAM1_0_ARGS      (TEE_ARGS_BASE+TEE_OFFSET_PARAM1_0_ARGS)
#define TEE_PARAM1_1_ARGS      (TEE_ARGS_BASE+TEE_OFFSET_PARAM1_1_ARGS)
#define TEE_PARAM2_0_ARGS      (TEE_ARGS_BASE+TEE_OFFSET_PARAM2_0_ARGS)
#define TEE_PARAM2_1_ARGS      (TEE_ARGS_BASE+TEE_OFFSET_PARAM2_1_ARGS)
#define TEE_PARAM3_0_ARGS      (TEE_ARGS_BASE+TEE_OFFSET_PARAM3_0_ARGS)
#define TEE_PARAM3_1_ARGS      (TEE_ARGS_BASE+TEE_OFFSET_PARAM3_1_ARGS)
#define TEE_CMDID_ARGS         (TEE_ARGS_BASE+TEE_OFFSET_CMDID_ARGS)
#define TEE_RETURN_ARGS        (TEE_ARGS_BASE+TEE_OFFSET_RETURN_ARGS)

#define TEE_SHM_BASE           0xA0000000

#endif /* TEE_DEFINES_H */
